# Generated by Django 4.2.7 on 2023-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbFitbit',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('hr', models.FloatField(blank=True, null=True)),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('coherence', models.FloatField(blank=True, null=True)),
                ('bm', models.IntegerField(blank=True, null=True)),
                ('sleep', models.IntegerField(blank=True, null=True)),
                ('eda', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('concentration_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_Fitbit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('device_check', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_Member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbSessionResult',
            fields=[
                ('session_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('input_place', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('concentration_score_avg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_Session_Result',
                'managed': False,
            },
        ),
    ]
