# Generated by Django 4.2.7 on 2023-12-05 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CandY_Server", "0002_tb_fitbit_tb_member_tb_session_result_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tb_fitbit",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="tb_member",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="tb_session_result",
            options={"managed": True},
        ),
    ]
