# Generated by Django 4.2.7 on 2023-12-05 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "CandY_Server",
            "0003_alter_tb_fitbit_options_alter_tb_member_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tb_fitbit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tb_member",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tb_session_result",
            options={},
        ),
    ]
